//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryARM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.TakedInfoes = new HashSet<TakedInfo>();
        }
    
        public int BookId { get; set; }
        public string Author { get; set; }
        public string Name { get; set; }
        public string ISBN { get; set; }
        public string BBK { get; set; }
        public string PublishingHouse { get; set; }
        public string PlacePublishing { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> CountOfLists { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Statute Statute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakedInfo> TakedInfoes { get; set; }
    }
}
