//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryARM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakedInfo
    {
        public int TakedBookId { get; set; }
        public string TicketNumber { get; set; }
        public string ISBN { get; set; }
        public Nullable<System.DateTime> TakedDay { get; set; }
        public Nullable<System.DateTime> ReturnDay { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
